### PR TITLE
Mobile 68 And Mobile 69

### PR DESCRIPTION
**Pull request by 07jasjeet**
1) Introduced Material3 Theming and applied theming to all composables.
2) Introduced Explicit App theme override in settings. [MOBILE-68]
3) Fixed status bar foreground on all activities. [MOBILE-69] (Nice)
4) Fixed a home screen bug where scrolling hard to the end caused gaps of white color to peek through.
5) Fixed system navigation background.

### CODE REVIEW

**Review by akshaaatt — APPROVED** [review]
Looks good to me! Just a note that for the commit messages, the last one says ListenBrainz instead of MusicBrainz. Try to rename those just for keeping the commits clean.

**Comment by 07jasjeet** [comment]
> Looks good to me! Just a note that for the commit messages, the last one says ListenBrainz instead of MusicBrainz. Try to rename those just for keeping the commits clean.

Oh sorry my bad :(
Should I do it now because you'll need to run the tests again if I did so.

**Comment by akshaaatt** [comment]
You can do it rn @07jasjeet

**Comment by 07jasjeet** [comment]
Done!

**Pull request merged**
