### PR TITLE
Asset Attributions

### PR DESCRIPTION
**Pull request by akshaaatt**
- Added Lottie Attributions

### CODE REVIEW

**Comment by amCap1712** [comment]
There are more assets here than those mentioned in the file. Can you please include all of the assets here? Some of those might be unused, feel free to remove those.

**Comment by akshaaatt** [comment]
@amCap1712 Thanks for pointing this out. I have finalized the attributions as of now. The Lottie ones are done. They were checked and only the ones used as per me have been attributed. Please merge this once #83 is final and done. 
In case there are any left resources, I will attribute them to the next PR.

**Comment by amCap1712** [comment]
@akshaaatt Can you please update the PR with the latest changes in assets if any?

**Comment by akshaaatt** [comment]
@amCap1712 On it.

**Comment by amCap1712** [comment]
Also, once this PR is merged we should add a link to this file in master branch in the About page of the app.

**Comment by akshaaatt** [comment]
@amCap1712 changes made :)

**Pull request merged**
