### PR TITLE
Kotlin Conversion

### PR DESCRIPTION
**Pull request by akshaaatt**
Carefully migrating from Java to Kotlin while testing everything to make sure the project is intact.

### CODE REVIEW

**Comment by akshaaatt** [comment]
@amCap1712 I have completed refactored the whole codebase to Kotlin except 2-3 Java classes which I thought you should review first. Other than that all seems good!

**Comment by amCap1712** [comment]
@akshaaatt Thanks for the contribution. Can you please rebase on the current master? Also, can you do a sanity check by testing the application on your device manually? It doesn't need to be exhaustive, whatever you can test is fine. I'll be testing on my end as well and if everything goes well, I'll merge the PR.

**Comment by akshaaatt** [comment]
Finally did it! I am so happy. It took me a while to do it but finally learned to do it!
Tested it as well.
@amCap1712 All done boss :)

**Comment by amCap1712** [comment]
Works great! Thanks!

**Pull request merged**
